specVersion: 0.0.1
description: Substrate slots auction data collector
repository: git@github.com:subvis-io/subquery-spectator.git
schema: ./schema.graphql
network:
  # endpoint: wss://polkadot.api.onfinality.io/public-ws
  endpoint: wss://rococo-rpc.polkadot.io
  
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 190453
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        #   filter:
        #     module: balances
        #     method: Deposit
        # - handler: handleCall
        #   kind: substrate/CallHandler
